name: template
description: "A new Flutter project for coffee shop management."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0        # Library database
  path: ^1.8.3           # Library untuk mengatur path database

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Mengaktifkan folder assets agar gambar kopi bisa muncul
  assets:
    - assets/images/